# Generated by Django 5.2.8 on 2026-01-01 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_fix_field_removals'),
    ]

    operations = [
        # Update ResidentPayment model structure
        migrations.AlterModelOptions(
            name='residentpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resident Payment', 'verbose_name_plural': 'Resident Payments'},
        ),
        migrations.RenameField(
            model_name='residentpayment',
            old_name='payment_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='residentpayment',
            name='appartement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payments',
                to='myapp.appartement'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentpayment',
            name='confirmed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Date syndic confirmed the payment',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='residentpayment',
            name='paid_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Date resident claims payment was made',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='residentpayment',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')],
                default='PENDING',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='residentpayment',
            name='syndic',
            field=models.ForeignKey(
                default=102,
                limit_choices_to={'role': 'SYNDIC'},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='validated_payments',
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residentpayment',
            name='charge',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payments',
                to='myapp.charge'
            ),
        ),
        migrations.AlterField(
            model_name='residentpayment',
            name='payment_method',
            field=models.CharField(
                choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('ONLINE', 'Online')],
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='residentpayment',
            name='reference',
            field=models.CharField(
                blank=True,
                help_text='Bank reference / receipt number',
                max_length=100,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='residentpayment',
            name='resident',
            field=models.ForeignKey(
                limit_choices_to={'role': 'RESIDENT'},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payments',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
