# Generated by Django 5.2.8 on 2026-01-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_payment_proof_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Upload payment proof (receipt, screenshot, etc.)', null=True, upload_to=''),
        ),
    ]
