# Generated by Django 5.2.8 on 2026-02-11 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_appartement_surface_area_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='SubscriptionPayment',
        ),
        migrations.RenameModel(
            old_name='ResidentPayment',
            new_name='ChargePayment',
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(
                choices=[('PAYPAL', 'Paypal'), ('STRIPE', 'Stripe')], 
                default='BANK_TRANSFER', 
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='chargepayment',
            name='payment_method',
            field=models.CharField(
                choices=[('BANK_TRANSFER', 'Bank Transfer'), ('PAYPAL', 'Paypal')], 
                max_length=20
            ),
        ),
    ]
