# Generated by Django 5.2.8 on 2026-02-25 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_payment_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Charge Payment', 'verbose_name_plural': 'Charge Payments'},
        ),
        migrations.AddField(
            model_name='reclamation',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='ai_urgency_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='category',
            field=models.CharField(blank=True, choices=[('PLUMBING', 'Plumbing'), ('ELECTRICITY', 'Electricity'), ('NOISE', 'Noise'), ('SECURITY', 'Security'), ('ELEVATOR', 'Elevator'), ('CLEANLINESS', 'Cleanliness'), ('ADMINISTRATIVE', 'Administrative'), ('PARKING', 'Parking'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='priority_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='suggested_department',
            field=models.CharField(blank=True, choices=[('MAINTENANCE', 'Maintenance'), ('SECURITY', 'Security'), ('ADMINISTRATION', 'Administration'), ('FINANCE', 'Finance'), ('CLEANING', 'Cleaning'), ('MANAGEMENT', 'Management')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chargepayment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Date syndic confirmed payment', null=True),
        ),
        migrations.AlterField(
            model_name='chargepayment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about payment'),
        ),
        migrations.AlterField(
            model_name='chargepayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Date the resident claims payment was made', null=True),
        ),
        migrations.AlterField(
            model_name='chargepayment',
            name='resident',
            field=models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='charge_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
