# Generated by Django 5.2.8 on 2026-03-05 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_chargepayment_options_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('RECLAMATION_CREATED', 'Reclamation Created'), ('RECLAMATION_UPDATED', 'Reclamation Updated'), ('CHARGE_CREATED', 'Charge Created'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('REUNION_SCHEDULED', 'Reunion Scheduled'), ('SYSTEM', 'System Notification')], max_length=30)),
                ('read', models.BooleanField(default=False)),
                ('related_entity_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
