# Generated by Django 5.2.8 on 2026-03-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_appartement_surface_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='syndic_profile',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='appartement',
            name='surface_area',
        ),
        migrations.RemoveField(
            model_name='chargepayment',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='cin',
        ),
        # migrations.RemoveField(
        #     model_name='syndicprofile',
        #     name='address',
        # ),
        # migrations.RemoveField(
        #     model_name='syndicprofile',
        #     name='company_name',
        # ),
        # migrations.RemoveField(
        #     model_name='syndicprofile',
        #     name='license_number',
        # ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='phone',
        # ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPayment',
        ),
    ]
