# Generated by Django 5.2.8 on 2026-03-12 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SYNDIC', 'Syndic'), ('RESIDENT', 'Resident')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_syndic', models.ForeignKey(blank=True, limit_choices_to={'role': 'SYNDIC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_residents', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'myapp_user',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('RECLAMATION_CREATED', 'Reclamation Created'), ('RECLAMATION_UPDATED', 'Reclamation Updated'), ('CHARGE_CREATED', 'Charge Created'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('REUNION_SCHEDULED', 'Reunion Scheduled'), ('SYSTEM', 'System Notification')], max_length=30)),
                ('read', models.BooleanField(default=False)),
                ('related_entity_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'myapp_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resident Profile',
                'verbose_name_plural': 'Resident Profiles',
                'db_table': 'myapp_residentprofile',
            },
        ),
        migrations.CreateModel(
            name='SyndicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rib', models.CharField(blank=True, help_text='RIB (Bank Identifier) for bank transfers', max_length=34, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'SYNDIC'}, on_delete=django.db.models.deletion.CASCADE, related_name='syndic_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Syndic Profile',
                'verbose_name_plural': 'Syndic Profiles',
                'db_table': 'myapp_syndicprofile',
            },
        ),
    ]
