# Generated by Django 5.2.8 on 2026-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('monthly_charge', models.DecimalField(decimal_places=2, help_text='Default monthly charge amount', max_digits=10)),
            ],
            options={
                'verbose_name': 'Appartement',
                'verbose_name_plural': 'Appartements',
                'db_table': 'myapp_appartement',
            },
        ),
    ]
