# Generated by Django 5.2.8 on 2026-03-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='immeuble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartements', to='buildings.immeuble'),
        ),
    ]
