# Generated by Django 5.2.8 on 2026-03-12 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='resident',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'RESIDENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appartements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='appartement',
            unique_together={('immeuble', 'number')},
        ),
    ]
