# Generated by Django 5.2.8 on 2026-03-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIALLY_PAID', 'Partially Paid')], default='UNPAID', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='apartments.appartement')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'db_table': 'myapp_charge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('PAYPAL', 'Paypal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Bank reference / receipt number', max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Date the resident claims payment was made', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about payment')),
                ('rib', models.CharField(blank=True, help_text='RIB for bank transfers', max_length=34, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Date syndic confirmed payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apartments.appartement')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.charge')),
            ],
            options={
                'verbose_name': 'Charge Payment',
                'verbose_name_plural': 'Charge Payments',
                'db_table': 'myapp_chargepayment',
                'ordering': ['-created_at'],
            },
        ),
    ]
