# Generated by Django 5.2.8 on 2026-03-12 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepayment',
            name='resident',
            field=models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='charge_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargepayment',
            name='syndic',
            field=models.ForeignKey(limit_choices_to={'role': 'SYNDIC'}, on_delete=django.db.models.deletion.CASCADE, related_name='validated_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
