# Generated by Django 5.2.8 on 2026-03-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_reclamationstatushistory',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('PLUMBING', 'Plumbing'), ('ELECTRICITY', 'Electricity'), ('NOISE', 'Noise'), ('SECURITY', 'Security'), ('ELEVATOR', 'Elevator'), ('CLEANLINESS', 'Cleanliness'), ('ADMINISTRATIVE', 'Administrative'), ('PARKING', 'Parking'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('ai_urgency_level', models.CharField(blank=True, max_length=20, null=True)),
                ('priority_score', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('suggested_department', models.CharField(blank=True, choices=[('MAINTENANCE', 'Maintenance'), ('SECURITY', 'Security'), ('ADMINISTRATION', 'Administration'), ('FINANCE', 'Finance'), ('CLEANING', 'Cleaning'), ('MANAGEMENT', 'Management')], max_length=20, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='apartments.appartement')),
            ],
            options={
                'verbose_name': 'Reclamation',
                'verbose_name_plural': 'Reclamations',
                'db_table': 'myapp_reclamation',
                'ordering': ['-created_at'],
            },
        ),
    ]
