# Generated by Django 5.2.8 on 2026-03-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('topic', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='buildings.immeuble')),
            ],
            options={
                'verbose_name': 'Reunion',
                'verbose_name_plural': 'Reunions',
                'db_table': 'myapp_reunion',
                'ordering': ['-date_time'],
            },
        ),
    ]
